#!/usr/bin/env python3
"""
Phase 1 — PoC Clustering and Visualisation.

Loads embedding .npy files generated by extract_embeddings.py,
runs UMAP dimensionality reduction + HDBSCAN clustering,
produces a self-contained HTML dashboard with:
  - UMAP scatter plot (coloured by method)
  - UMAP scatter plot (coloured by cluster)
  - Per-method statistics table
  - Cluster size distribution

Usage:
    # Preferred (schema layout):
    python cluster_poc.py --embeddings /Volumes/WD2TB/sea-data/2A400/embeddings/birdnet
    # Legacy flat layout still works:
    python cluster_poc.py --embeddings /Volumes/WD2TB/sea-data/2A400/embeddings
    python cluster_poc.py --embeddings .../embeddings/birdnet --date 2026-03-19
"""

import argparse
import json
import os
import sys
import time
from typing import Any, Dict, List, Optional, Tuple

import numpy as np

def convert_numpy_types(obj):
    """Recursively convert numpy types to Python native types for JSON serialization."""
    if isinstance(obj, np.integer):
        return int(obj)
    elif isinstance(obj, np.floating):
        return float(obj)
    elif isinstance(obj, np.ndarray):
        return obj.tolist()
    elif isinstance(obj, dict):
        return {k: convert_numpy_types(v) for k, v in obj.items()}
    elif isinstance(obj, list):
        return [convert_numpy_types(item) for item in obj]
    elif isinstance(obj, tuple):
        return tuple(convert_numpy_types(item) for item in obj)
    return obj

try:
    from config import ANALYSIS_OUTPUT
except ImportError:
    ANALYSIS_OUTPUT = "/Volumes/WD2TB/sea-data"

EMBEDDING_DIM = 1024

# ── Load embeddings ─────────────────────────────────────

CACHE_SUFFIX = "_dashboard_cache.json"


def save_cache(cache_path: str, emb_dir: str, umap_2d: np.ndarray,
               y_method: np.ndarray, method_names: List[str],
               cluster_labels: np.ndarray, stats: Dict[str, Any]):
    """Serialize analysis results to JSON so we can regenerate HTML later."""
    cache = {
        "emb_dir": emb_dir,
        "umap_2d": umap_2d.tolist(),
        "method_labels": [int(x) for x in y_method],
        "method_names": method_names,
        "cluster_labels": [int(x) for x in cluster_labels],
        "stats": convert_numpy_types(stats),
    }
    with open(cache_path, "w") as f:
        json.dump(cache, f, indent=2, ensure_ascii=False)
    print(f"  ⏬  Cache saved to {cache_path}")


def load_cache(cache_path: str):
    """Load cached analysis results."""
    with open(cache_path, "r") as f:
        cache = json.load(f)
    return (np.array(cache["umap_2d"]),
            np.array(cache["method_labels"]),
            cache["method_names"],
            np.array(cache["cluster_labels"]),
            cache["stats"],
            cache["emb_dir"])


def load_embeddings(
    emb_dir: str,
    methods: List[str],
    date_filter: Optional[List[str]] = None,
) -> Tuple[Dict[str, np.ndarray], Dict[str, np.ndarray], Dict[str, List[Dict]]]:
    """Load all embeddings and metadata from *emb_dir*.

    Returns:
        embeddings: dict method → (N, 1024) float32
        methods_per_row: (K,) int8 — method index for each row
        row_meta: list of metadata dicts (1:1 with rows)
    """
    all_emb: Dict[str, List[np.ndarray]] = {m: [] for m in methods}
    all_meta: Dict[str, List[Dict]] = {m: [] for m in methods}

    for fname in sorted(os.listdir(emb_dir)):
        if not fname.endswith("_embeddings.npy"):
            continue
        # Extract date and method from filename: YYYY-MM-DD_METHOD_embeddings.npy
        try:
            parts = fname.replace("_embeddings.npy", "").split("_", 3)
            date_str = parts[0]
            method = "_".join(parts[1:])
        except ValueError:
            continue

        if date_filter and date_str not in date_filter:
            continue
        if method not in methods:
            continue

        emb_path = os.path.join(emb_dir, fname)
        meta_path = emb_path.replace("_embeddings.npy", "_meta.json")

        if not os.path.isfile(emb_path):
            continue

        emb = np.load(emb_path).astype(np.float32)
        if emb.ndim == 1:
            emb = emb.reshape(1, -1)

        meta: List[Dict] = []
        if os.path.isfile(meta_path):
            with open(meta_path, "r") as f:
                meta = json.load(f)

        all_emb[method].append(emb)
        all_meta[method].extend(meta)

        print(f"  {fname}: {len(emb)} embeddings")

    # Concatenate
    embeddings: Dict[str, np.ndarray] = {}
    for m in methods:
        if all_emb[m]:
            embeddings[m] = np.concatenate(all_emb[m], axis=0)
        else:
            embeddings[m] = np.zeros((0, EMBEDDING_DIM), dtype=np.float32)

    # Flatten for clustering
    stacked = []
    method_ids = []
    flat_meta = []
    for i, m in enumerate(methods):
        n = len(embeddings[m])
        if n > 0:
            stacked.append(embeddings[m])
            method_ids.append(np.full(n, i, dtype=np.int8))
            flat_meta.extend(all_meta[m])

    if not stacked:
        return embeddings, np.array([], dtype=np.int8), []

    X = np.concatenate(stacked, axis=0).astype(np.float32)
    y_method = np.concatenate(method_ids)

    return embeddings, X, y_method, flat_meta, methods


# ── Noise Reference ─────────────────────────────────────

def load_noise_embeddings(emb_dir: str) -> Optional[Dict[str, np.ndarray]]:
    """Load noise reference embeddings if available.

    Returns:
        Dict group_name → (N, 1024) mean noise vector per group, or None.
    """
    noise_paths = [
        f for f in os.listdir(emb_dir)
        if f.startswith("noise_") and f.endswith("_embeddings.npy")
    ]
    if not noise_paths:
        return None

    noise_vectors: Dict[str, np.ndarray] = {}
    for fname in noise_paths:
        group = fname.replace("noise_", "").replace("_embeddings.npy", "")
        path = os.path.join(emb_dir, fname)
        emb = np.load(path).astype(np.float32)
        if emb.ndim == 1:
            emb = emb.reshape(1, -1)
        # L2-normalise and compute mean vector
        norms = np.linalg.norm(emb, axis=1, keepdims=True)
        norms = np.where(norms == 0, 1.0, norms)
        emb_norm = emb / norms
        noise_vectors[group] = np.mean(emb_norm, axis=0).astype(np.float32)
        print(f"  noise_{group}: {len(emb)} embeddings → mean vector")

    return noise_vectors


def compute_noise_distance(
    X: np.ndarray,
    y_method: np.ndarray,
    method_names: List[str],
    cluster_labels: np.ndarray,
    noise_vectors: Dict[str, np.ndarray],
    shared_analysis: Optional[Dict[str, Any]] = None,
) -> Dict[str, Any]:
    """Compute cosine similarity of each cluster embedding to noise reference.

    Returns per-cluster and per-method noise similarity stats,
    plus top shared clusters with per-method noise distance breakdown.
    """
    # Map methods to their own noise groups (apples-to-apples comparison)
    # bf_LabIR → noise_LabIR, bf_SPIR → noise_SPIR, sa → noise_sa, mono → noise_mono
    # Omitting a method is fine — SA/Mono noise refs may not exist yet
    method_to_noise: Dict[str, str] = {}
    for method in method_names:
        noise_group = method.replace("bf_", "")  # bf_LabIR→LabIR, bf_SPIR→SPIR, sa→sa, mono→mono
        if noise_group in noise_vectors:
            method_to_noise[method] = noise_group

    if not method_to_noise:
        return {}

    # L2-normalise all embeddings
    norms = np.linalg.norm(X, axis=1, keepdims=True)
    norms = np.where(norms == 0, 1.0, norms)
    X_norm = X / norms

    # Compute noise similarity per embedding
    noise_sim = np.zeros(len(X), dtype=np.float32)
    for i, method in enumerate(method_names):
        mask = y_method == i
        if method in method_to_noise:
            noise_vec = noise_vectors[method_to_noise[method]]
            noise_sim[mask] = np.dot(X_norm[mask], noise_vec)

    # Per-method mean noise similarity
    per_method: List[Dict] = []
    for i, method in enumerate(method_names):
        mask = y_method == i
        if np.sum(mask) > 0:
            mean_sim = float(np.mean(noise_sim[mask]))
            per_method.append({
                "method": method,
                "mean_noise_sim": round(mean_sim, 4),
                "mean_noise_distance": round(1.0 - mean_sim, 4),
            })

    # Per-cluster noise similarity
    per_cluster: List[Dict] = []
    for cid in sorted(set(cluster_labels)):
        if cid == -1:
            continue
        mask = cluster_labels == cid
        if np.sum(mask) > 0:
            mean_sim = float(np.mean(noise_sim[mask]))
            per_cluster.append({
                "cluster_id": int(cid),
                "size": int(np.sum(mask)),
                "mean_noise_sim": round(mean_sim, 4),
                "mean_noise_distance": round(1.0 - mean_sim, 4),
            })

    # ── Top shared clusters with per-method noise distance breakdown ──
    top_shared_clusters: List[Dict] = []
    if shared_analysis is not None:
        # Build cluster_id → tier lookup from shared analysis
        cluster_tier: Dict[int, int] = {}
        for c in shared_analysis.get("clusters", []):
            cluster_tier[c["cluster_id"]] = c["tier"]

        # Process each cluster in tiers 1-3
        for cid in sorted(set(cluster_labels)):
            if cid == -1:
                continue
            tier = cluster_tier.get(cid)
            if tier is None or tier > 3:
                continue

            cluster_mask = cluster_labels == cid
            cluster_size_val = int(np.sum(cluster_mask))
            method_breakdown: List[Dict] = []
            cluster_noise_distances: List[float] = []

            for i, method in enumerate(method_names):
                method_mask = (y_method == i) & cluster_mask
                n_method = int(np.sum(method_mask))
                if n_method > 0:
                    mean_sim = float(np.mean(noise_sim[method_mask]))
                    nd = round(1.0 - mean_sim, 4)
                    method_breakdown.append({
                        "method": method,
                        "n": n_method,
                        "noise_distance": nd,
                    })
                    cluster_noise_distances.append(nd)

            if method_breakdown:
                mean_nd = round(float(np.mean(cluster_noise_distances)), 4)
                top_shared_clusters.append({
                    "cluster_id": int(cid),
                    "size": cluster_size_val,
                    "tier": tier,
                    "mean_noise_distance": mean_nd,
                    "method_breakdown": method_breakdown,
                })

        # Sort by mean noise distance descending, take top 10
        top_shared_clusters.sort(key=lambda c: c["mean_noise_distance"], reverse=True)
        top_shared_clusters = top_shared_clusters[:10]

    return {
        "per_method": per_method,
        "per_cluster": per_cluster,
        "available": True,
        "top_shared_clusters": top_shared_clusters,
    }

# ── UMAP ────────────────────────────────────────────────

def run_umap(X: np.ndarray, n_components: int = 2, n_neighbors: int = 30,
             min_dist: float = 0.1, random_state: int = 42) -> np.ndarray:
    """Reduce *X* to *n_components* dimensions via UMAP."""
    import umap
    import warnings
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        reducer = umap.UMAP(
            n_components=n_components,
            n_neighbors=n_neighbors,
            min_dist=min_dist,
            random_state=random_state,
            n_jobs=1,  # parallelism doesn't work with random_state set; keep 1
            verbose=False,
        )
        return reducer.fit_transform(X)


# ── HDBSCAN ─────────────────────────────────────────────

def run_hdbscan(X: np.ndarray, min_cluster_size: int = 5,
                min_samples: int = 3) -> np.ndarray:
    """Cluster *X* with HDBSCAN.  Returns label array (-1 = noise).

    For speed on real datasets, callers should pass the UMAP 2D
    projection rather than the raw 1024D embeddings.  UMAP preserves
    topological structure, so clusters in 2D ≈ clusters in 1024D.
    """
    import hdbscan
    clusterer = hdbscan.HDBSCAN(
        min_cluster_size=min_cluster_size,
        min_samples=min_samples,
        prediction_data=True,
    )
    return clusterer.fit_predict(X)


def compute_intra_method_cosine(embeddings: Dict[str, np.ndarray],
                                method_names: List[str]) -> List[float]:
    """Compute mean pairwise cosine similarity per method — O(nd).

    Higher values = more consistent acoustic features = better SNR.

    Uses the identity  ∑_{i≠j} x_i·x_j  =  ‖∑x_i‖² - n
    (since each x_i is L2-normalized, self-dot = 1).
    Avoids materialising the O(n²) Gram matrix.
    """
    results = []
    for method in method_names:
        X = embeddings.get(method)
        if X is None or X.shape[0] < 2:
            results.append(0.0)
            continue
        # L2 normalize each row
        norms = np.linalg.norm(X, axis=1, keepdims=True)
        norms = np.where(norms == 0, 1.0, norms)
        X_norm = X / norms
        n = X_norm.shape[0]
        # sum_vec = Σ x_i  →  ‖sum_vec‖² = Σ_{i,j} x_i·x_j
        sum_vec = np.sum(X_norm, axis=0)  # (D,)
        total = float(np.dot(sum_vec, sum_vec))
        mean_cos = (total - n) / (n * (n - 1))
        results.append(round(mean_cos, 4))
    return results


# ── Statistics ──────────────────────────────────────────

def compute_stats(X: np.ndarray, y_method: np.ndarray, method_names: List[str],
                  cluster_labels: np.ndarray,
                  embeddings: Optional[Dict[str, np.ndarray]] = None,
                  ) -> Dict[str, Any]:
    """Compute per-method, per-cluster, and SNR-proxy statistics."""
    stats: Dict[str, Any] = {"per_method": [], "per_cluster": [],
                              "overview": {}, "snr_proxy": {}}

    n_clusters = len(set(cluster_labels)) - (1 if -1 in cluster_labels else 0)
    n_noise = int(np.sum(cluster_labels == -1))

    stats["overview"] = {
        "total_embeddings": int(len(X)),
        "n_clusters": n_clusters,
        "n_noise": n_noise,
        "noise_pct": round(n_noise / max(len(X), 1) * 100, 1),
        "embedding_dim": X.shape[1],
    }

    for i, method in enumerate(method_names):
        mask = y_method == i
        n = int(np.sum(mask))
        labels = cluster_labels[mask]
        n_in_cluster = int(np.sum(labels >= 0))
        n_noise_m = int(np.sum(labels == -1))
        unique_clusters = len(set(labels[labels >= 0]))

        stats["per_method"].append({
            "method": method,
            "n_embeddings": n,
            "n_in_cluster": n_in_cluster,
            "n_noise": n_noise_m,
            "noise_pct": round(n_noise_m / max(n, 1) * 100, 1),
            "n_unique_clusters": unique_clusters,
        })

    # ── SNR Proxy: intra-method cosine similarity ──
    if embeddings is not None:
        cos_sims = compute_intra_method_cosine(embeddings, method_names)
        stats["snr_proxy"] = {
            "cosine_similarity": [
                {"method": m, "value": v}
                for m, v in zip(method_names, cos_sims)
            ],
            "method_order": method_names,
        }
        # Also attach cosine similarity to per-method entries
        for i, v in enumerate(cos_sims):
            stats["per_method"][i]["cosine_sim"] = v

    for cid in sorted(set(cluster_labels)):
        if cid == -1:
            continue
        mask = cluster_labels == cid
        total = int(np.sum(mask))
        by_method = {}
        for i, method in enumerate(method_names):
            m_count = int(np.sum((y_method == i) & mask))
            by_method[method] = m_count
        stats["per_cluster"].append({
            "cluster_id": int(cid),
            "size": total,
            "by_method": by_method,
        })

    return stats


# ── Shared Cluster & Angular Diversity Analysis ──────────

def compute_shared_cluster_analysis(
    X: np.ndarray,
    cluster_labels: np.ndarray,
    y_method: np.ndarray,
    method_names: List[str],
    metadata: List[Dict],
) -> Dict[str, Any]:
    """Analyze shared clusters, angular diversity, and within-cluster coherence.
    
    Returns detailed per-cluster statistics including:
    - Which methods are present in each cluster
    - Within-cluster coherence (cosine similarity) per method
    - Angular diversity (unique azimuths) for beamforming methods
    - Stratification tier (how many methods share this cluster)
    
    Stratification tiers:
    - Tier 1: All 4 methods present (most robust)
    - Tier 2: 3 methods present
    - Tier 3: 2 methods present (shared cluster threshold)
    - Tier 4: Beamforming-only (only bf_LabIR and/or bf_SPIR)
    - Tier 5: Mono-only or SA-only
    """
    analysis = {
        "clusters": [],
        "summary": {
            "tier_1_all_methods": 0,
            "tier_2_three_methods": 0,
            "tier_3_two_methods": 0,
            "tier_4_bf_only": 0,
            "tier_5_mono_sa_only": 0,
            "noise": 0,
        },
        "angular_diversity": {},
    }
    
    # Identify beamforming methods
    bf_methods = {"bf_LabIR", "bf_SPIR"}
    non_bf_methods = set(method_names) - bf_methods
    
    # L2 normalize all embeddings
    norms = np.linalg.norm(X, axis=1, keepdims=True)
    norms = np.where(norms == 0, 1.0, norms)
    X_norm = X / norms
    
    # Analyze each cluster
    for cid in sorted(set(cluster_labels)):
        if cid == -1:
            analysis["summary"]["noise"] = int(np.sum(cluster_labels == -1))
            continue
        
        cluster_mask = cluster_labels == cid
        cluster_indices = np.where(cluster_mask)[0]
        cluster_size = len(cluster_indices)
        
        # Which methods are present?
        methods_present = {}
        for i, method in enumerate(method_names):
            method_mask = (y_method == i) & cluster_mask
            count = int(np.sum(method_mask))
            if count > 0:
                methods_present[method] = count
        
        n_methods = len(methods_present)
        
        # Determine tier
        if n_methods == len(method_names):
            tier = 1
            analysis["summary"]["tier_1_all_methods"] += 1
        elif n_methods == 3:
            tier = 2
            analysis["summary"]["tier_2_three_methods"] += 1
        elif n_methods == 2:
            tier = 3
            analysis["summary"]["tier_3_two_methods"] += 1
        elif all(m in bf_methods for m in methods_present.keys()):
            tier = 4
            analysis["summary"]["tier_4_bf_only"] += 1
        else:
            tier = 5
            analysis["summary"]["tier_5_mono_sa_only"] += 1
        
        # Within-cluster coherence per method
        coherence_per_method = {}
        for method, count in methods_present.items():
            method_mask = np.array([metadata[idx]["method"] == method for idx in cluster_indices])
            method_indices = cluster_indices[method_mask]
            
            if len(method_indices) >= 2:
                X_method = X_norm[method_indices]
                # Mean pairwise cosine similarity
                sum_vec = np.sum(X_method, axis=0)
                total = float(np.dot(sum_vec, sum_vec))
                n = len(method_indices)
                mean_cos = (total - n) / (n * (n - 1))
                coherence_per_method[method] = round(mean_cos, 4)
            else:
                coherence_per_method[method] = None
        
        # Angular diversity (for beamforming methods)
        azimuths = set()
        elevations = set()
        for idx in cluster_indices:
            meta = metadata[idx]
            if meta.get("azimuth") is not None:
                azimuths.add(meta["azimuth"])
            if meta.get("elevation") is not None:
                elevations.add(meta["elevation"])
        
        angular_diversity = {
            "unique_azimuths": len(azimuths),
            "azimuths": sorted(list(azimuths)) if azimuths else [],
            "unique_elevations": len(elevations),
            "elevations": sorted(list(elevations)) if elevations else [],
        }
        
        # Store in angular_diversity dict for plotting
        if angular_diversity["unique_azimuths"] > 0:
            analysis["angular_diversity"][int(cid)] = angular_diversity["azimuths"]
        
        # Build cluster record
        cluster_record = {
            "cluster_id": int(cid),
            "size": cluster_size,
            "tier": tier,
            "methods_present": methods_present,
            "n_methods": n_methods,
            "coherence_per_method": coherence_per_method,
            "angular_diversity": angular_diversity,
        }
        analysis["clusters"].append(cluster_record)
    
    return analysis



# ── HTML generation ─────────────────────────────────────

def generate_html(
    emb_dir: str,
    umap_2d: np.ndarray,
    y_method: np.ndarray,
    method_names: List[str],
    cluster_labels: np.ndarray,
    stats: Dict[str, Any],
) -> str:
    """Generate a self-contained HTML dashboard with adaptive theming."""

    # Embed JSON data directly in HTML
    umap_s = json.dumps(umap_2d.tolist())
    method_s = json.dumps([int(x) for x in y_method])
    cluster_s = json.dumps([int(x) for x in cluster_labels])
    method_names_s = json.dumps(method_names)
    stats_s = json.dumps(convert_numpy_types(stats))

    return f"""<!DOCTYPE html>
<html lang="en-GB">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Acoustic Embedding Analysis — {emb_dir}</title>
<script src="https://cdn.plot.ly/plotly-2.32.0.min.js"></script>
<style>
:root {{
  --bg-primary: #ffffff;
  --bg-secondary: #f8fafc;
  --bg-card: #ffffff;
  --text-primary: #1e293b;
  --text-secondary: #64748b;
  --text-muted: #94a3b8;
  --border: #e2e8f0;
  --shadow: rgba(0, 0, 0, 0.05);
  --plot-bg: #ffffff;
  --plot-paper: #ffffff;
  --grid-color: #e2e8f0;
  --stat-bg: #f1f5f9;
}}

@media (prefers-color-scheme: dark) {{
  :root {{
    --bg-primary: #0f172a;
    --bg-secondary: #1e293b;
    --bg-card: #1e293b;
    --text-primary: #e2e8f0;
    --text-secondary: #cbd5e1;
    --text-muted: #94a3b8;
    --border: #334155;
    --shadow: rgba(0, 0, 0, 0.3);
    --plot-bg: #1e293b;
    --plot-paper: #1e293b;
    --grid-color: #334155;
    --stat-bg: #0f172a;
  }}
}}

[data-theme="dark"] {{
  --bg-primary: #0f172a;
  --bg-secondary: #1e293b;
  --bg-card: #1e293b;
  --text-primary: #e2e8f0;
  --text-secondary: #cbd5e1;
  --text-muted: #94a3b8;
  --border: #334155;
  --shadow: rgba(0, 0, 0, 0.3);
  --plot-bg: #1e293b;
  --plot-paper: #1e293b;
  --grid-color: #334155;
  --stat-bg: #0f172a;
}}

[data-theme="light"] {{
  --bg-primary: #ffffff;
  --bg-secondary: #f8fafc;
  --bg-card: #ffffff;
  --text-primary: #1e293b;
  --text-secondary: #64748b;
  --text-muted: #94a3b8;
  --border: #e2e8f0;
  --shadow: rgba(0, 0, 0, 0.05);
  --plot-bg: #ffffff;
  --plot-paper: #ffffff;
  --grid-color: #e2e8f0;
  --stat-bg: #f1f5f9;
}}

* {{ box-sizing: border-box; margin: 0; padding: 0; }}

body {{
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Inter', sans-serif;
  background: var(--bg-primary);
  color: var(--text-primary);
  padding: 32px 24px;
  line-height: 1.6;
  transition: background 0.3s ease, color 0.3s ease;
}}

.container {{
  max-width: 1400px;
  margin: 0 auto;
}}

header {{
  display: flex;
  justify-content: space-between;
  align-items: flex-start;
  margin-bottom: 32px;
  padding-bottom: 24px;
  border-bottom: 1px solid var(--border);
}}

h1 {{
  font-size: 1.75rem;
  font-weight: 700;
  margin-bottom: 8px;
  letter-spacing: -0.02em;
}}

.subtitle {{
  color: var(--text-secondary);
  font-size: 0.875rem;
  font-family: 'SF Mono', 'Monaco', monospace;
}}

.theme-toggle {{
  background: var(--bg-secondary);
  border: 1px solid var(--border);
  color: var(--text-primary);
  padding: 8px 16px;
  border-radius: 8px;
  cursor: pointer;
  font-size: 0.875rem;
  transition: all 0.2s ease;
}}

.theme-toggle:hover {{
  background: var(--border);
}}

h2 {{
  font-size: 1.125rem;
  font-weight: 600;
  margin: 32px 0 8px;
  color: var(--text-primary);
  letter-spacing: -0.01em;
}}

.description {{
  color: var(--text-secondary);
  font-size: 0.875rem;
  margin-bottom: 16px;
  line-height: 1.5;
}}

.card {{
  background: var(--bg-card);
  border: 1px solid var(--border);
  border-radius: 12px;
  padding: 24px;
  margin-bottom: 24px;
  box-shadow: 0 1px 3px var(--shadow);
  transition: background 0.3s ease, border-color 0.3s ease;
}}

.plot {{
  width: 100%;
  min-height: 500px;
}}

.plot-small {{
  min-height: 350px;
}}

.stats-grid {{
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(180px, 1fr));
  gap: 16px;
  margin-bottom: 32px;
}}

.stat-card {{
  background: var(--stat-bg);
  border-radius: 10px;
  padding: 20px;
  text-align: center;
  transition: background 0.3s ease;
}}

.stat-value {{
  font-size: 2.25rem;
  font-weight: 700;
  color: var(--text-primary);
  line-height: 1;
  margin-bottom: 6px;
}}

.stat-label {{
  font-size: 0.75rem;
  font-weight: 600;
  color: var(--text-muted);
  text-transform: uppercase;
  letter-spacing: 0.05em;
}}

table {{
  width: 100%;
  border-collapse: collapse;
  font-size: 0.875rem;
}}

th, td {{
  padding: 12px 16px;
  text-align: right;
  border-bottom: 1px solid var(--border);
}}

th {{
  color: var(--text-muted);
  font-weight: 600;
  text-transform: uppercase;
  font-size: 0.75rem;
  letter-spacing: 0.05em;
  background: var(--bg-secondary);
}}

td:first-child, th:first-child {{
  text-align: left;
}}

tr:hover td {{
  background: var(--bg-secondary);
}}

/* Noise Distance — Top Shared Clusters */
.noise-cluster-row {{
  border-bottom: 1px solid var(--border);
  padding: 12px 0;
  cursor: pointer;
  transition: background 0.15s ease;
}}

.noise-cluster-row:hover {{
  background: var(--bg-secondary);
}}

.noise-cluster-header {{
  display: flex;
  align-items: center;
  gap: 12px;
  margin-bottom: 6px;
}}

.noise-cluster-name {{
  font-weight: 600;
  font-size: 0.9rem;
  min-width: 90px;
}}

.noise-cluster-size {{
  color: var(--text-muted);
  font-size: 0.8rem;
  min-width: 60px;
}}

.noise-tier-badge {{
  display: inline-block;
  padding: 2px 8px;
  border-radius: 4px;
  font-size: 0.7rem;
  font-weight: 700;
  letter-spacing: 0.04em;
  text-transform: uppercase;
}}

.tier-1 {{ background: #fbbf24; color: #92400e; }}
.tier-2 {{ background: #cbd5e1; color: #475569; }}
.tier-3 {{ background: #d6a87c; color: #7c3a1e; }}

[data-theme="dark"] .tier-1 {{ background: #f59e0b; color: #78350f; }}
[data-theme="dark"] .tier-2 {{ background: #94a3b8; color: #334155; }}
[data-theme="dark"] .tier-3 {{ background: #b67b50; color: #fce7d5; }}

.noise-bar-wrapper {{
  flex: 1;
  display: flex;
  align-items: center;
  gap: 4px;
}}

.noise-bar-segment {{
  height: 8px;
  border-radius: 4px;
  min-width: 2px;
  transition: width 0.3s ease;
}}

.noise-detail {{
  display: none;
  padding: 8px 16px 8px 108px;
  font-size: 0.8rem;
  color: var(--text-secondary);
}}

.noise-detail.visible {{
  display: block;
}}

.noise-detail-row {{
  display: flex;
  align-items: center;
  gap: 16px;
  padding: 3px 0;
}}

.noise-detail-colour {{
  width: 10px;
  height: 10px;
  border-radius: 2px;
  flex-shrink: 0;
}}

.noise-detail-method {{
  min-width: 70px;
  font-weight: 500;
}}

.noise-detail-n {{
  min-width: 50px;
  color: var(--text-muted);
}}

.noise-detail-val {{
  font-variant-numeric: tabular-nums;
}}

.badge {{
  display: inline-block;
  padding: 4px 10px;
  border-radius: 6px;
  font-size: 0.75rem;
  font-weight: 600;
}}

.badge-mono {{ background: #eab30822; color: #ca8a04; }}
.badge-sa {{ background: #22c55e22; color: #16a34a; }}
.badge-labir {{ background: #3b82f622; color: #2563eb; }}
.badge-spir {{ background: #8b5cf622; color: #7c3aed; }}

[data-theme="dark"] .badge-mono {{ background: #eab30833; color: #facc15; }}
[data-theme="dark"] .badge-sa {{ background: #22c55e33; color: #4ade80; }}
[data-theme="dark"] .badge-labir {{ background: #3b82f633; color: #60a5fa; }}
[data-theme="dark"] .badge-spir {{ background: #8b5cf633; color: #a78bfa; }}

.two-col {{
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(500px, 1fr));
  gap: 24px;
}}

@media (max-width: 1024px) {{
  .two-col {{
    grid-template-columns: 1fr;
  }}
}}
</style>
</head>
<body>
<div class="container">

<header>
  <div>
    <h1>Acoustic Embedding Analysis</h1>
    <div class="subtitle">{emb_dir}</div>
  </div>
  <button class="theme-toggle" onclick="toggleTheme()">Toggle Theme</button>
</header>

<div class="stats-grid" id="overview"></div>

<h2>Dimensionality Reduction</h2>
<p class="description">UMAP projection of 1024-dimensional embeddings into 2D space. Clusters represent groups of acoustically similar recordings. Points are coloured by processing method to reveal method-specific patterns.</p>
<div class="card"><div class="plot" id="plot-method"></div></div>

<h2>Cluster Structure</h2>
<p class="description">Same UMAP projection coloured by HDBSCAN cluster assignment. Noise points (grey) represent embeddings that do not belong to any dense cluster. Each cluster may correspond to a distinct acoustic signature.</p>
<div class="card"><div class="plot" id="plot-cluster"></div></div>

<h2>Cluster Size Distribution</h2>
<p class="description">Number of embeddings assigned to each cluster. Larger clusters may represent more common or persistent acoustic patterns in the dataset.</p>
<div class="card"><div class="plot plot-small" id="plot-dist"></div></div>

<h2>Shared Cluster Analysis</h2>
<p class="description">Clusters detected by multiple methods indicate robust acoustic signatures. Tier 1 clusters (all 4 methods) represent the most reliable detections. Beamforming-only clusters (Tier 4) may reveal signals too weak for omnidirectional methods.</p>
<div class="card">
  <div class="stats-grid" id="shared-summary"></div>
  <div style="margin-top: 24px;">
    <h3 style="font-size: 1rem; margin-bottom: 12px; color: var(--text-primary);">Top Shared Clusters (Tier 1-3)</h3>
    <div id="table-shared-clusters"></div>
  </div>
</div>

<div class="two-col">
  <div>
    <h2>Angular Diversity</h2>
    <p class="description">For beamforming methods, the number of unique azimuth angles per cluster indicates directional coverage. Clusters with high angular diversity suggest omnidirectional or spatially distributed sources.</p>
    <div class="card"><div class="plot plot-small" id="plot-angular"></div></div>
  </div>
  <div>
    <h2>Within-Cluster Coherence</h2>
    <p class="description">Mean cosine similarity between embeddings within shared clusters, broken down by method. Higher coherence suggests more consistent acoustic features for that cluster.</p>
    <div class="card"><div class="plot plot-small" id="plot-coherence"></div></div>
  </div>
</div>

<div class="two-col">
  <div>
    <h2>Noise Distance (Per Method)</h2>
    <p class="description">Mean cosine distance of each method's embeddings from the noise reference. Higher distance indicates better signal separation from ambient noise. Beamforming should show larger distances due to directional gain.</p>
    <div class="card"><div class="plot plot-small" id="plot-noise-dist-method"></div></div>
  </div>
  <div>
    <h2>Noise Distance (Top Shared Clusters)</h2>
    <p class="description">Cosine distance from noise reference for top shared clusters, broken down by method. Compare whether beamforming generates embeddings farther from noise within the same acoustic signatures.</p>
    <div class="card"><div class="plot plot-small" id="plot-noise-dist-cluster"></div></div>
  </div>
</div>

<h2 id="noise-shared-heading" style="display:none;">🔇 Noise Distance — Top Shared Clusters</h2>
<p class="description" id="noise-shared-desc" style="display:none;">Per-method noise distance breakdown within the top 10 shared clusters (Tier 1-3), sorted by highest mean noise distance. Each bar's width represents how far that method's embeddings sit from ambient noise — longer bars indicate better signal separation.</p>
<div class="card" id="card-noise-shared" style="display:none;">
  <div id="noise-shared-list"></div>
</div>

</div>

<script>
const umapData = {umap_s};
const methodArr = {method_s};
const clusterArr = {cluster_s};
const methodNames = {method_names_s};
const stats = {stats_s};

const methodColors = ['#3b82f6', '#8b5cf6', '#22c55e', '#eab308'];
const clusterPalette = ['#ef4444','#3b82f6','#8b5cf6','#22c55e','#eab308','#f97316',
                         '#06b6d4','#ec4899','#84cc16','#6366f1','#14b8a6','#f43f5e',
                         '#0ea5e9','#a855f7','#eab308','#10b981','#d946ef','#64748b'];

// Theme management
function getTheme() {{
  const stored = localStorage.getItem('theme');
  if (stored) return stored;
  return window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light';
}}

function applyTheme(theme) {{
  document.documentElement.setAttribute('data-theme', theme);
  localStorage.setItem('theme', theme);
  updatePlotsTheme();
}}

function toggleTheme() {{
  const current = document.documentElement.getAttribute('data-theme') || getTheme();
  applyTheme(current === 'dark' ? 'light' : 'dark');
}}

function getPlotColors() {{
  const theme = document.documentElement.getAttribute('data-theme') || getTheme();
  return {{
    plot_bgcolor: theme === 'dark' ? '#1e293b' : '#ffffff',
    paper_bgcolor: theme === 'dark' ? '#1e293b' : '#ffffff',
    font_color: theme === 'dark' ? '#94a3b8' : '#64748b',
    grid_color: theme === 'dark' ? '#334155' : '#e2e8f0',
    legend_bg: theme === 'dark' ? '#0f172a' : '#ffffff',
  }};
}}

function updatePlotsTheme() {{
  const colors = getPlotColors();
  ['plot-method', 'plot-cluster', 'plot-dist', 'plot-angular', 'plot-coherence', 'plot-noise-dist-method', 'plot-noise-dist-cluster'].forEach(id => {{
    const el = document.getElementById(id);
    if (el && el.data) {{
      Plotly.relayout(id, {{
        plot_bgcolor: colors.plot_bgcolor,
        paper_bgcolor: colors.paper_bgcolor,
        'font.color': colors.font_color,
        'xaxis.color': colors.font_color,
        'yaxis.color': colors.font_color,
        'xaxis.gridcolor': colors.grid_color,
        'yaxis.gridcolor': colors.grid_color,
        'legend.bgcolor': colors.legend_bg,
      }});
    }}
  }});
}}

// Initialise theme
applyTheme(getTheme());

// Overview stats
const ov = stats.overview;
document.getElementById('overview').innerHTML = [
  {{ label: 'Total Embeddings', value: ov.total_embeddings.toLocaleString() }},
  {{ label: 'Clusters Found', value: ov.n_clusters.toLocaleString() }},
  {{ label: 'Embedding Dimension', value: ov.embedding_dim }},
].map(s => `<div class="stat-card"><div class="stat-value">${{s.value}}</div><div class="stat-label">${{s.label}}</div></div>`).join('');

// UMAP by method
const colors = getPlotColors();
var traceMethod = methodNames.map((name, i) => {{
    const mask = methodArr.map(m => m === i);
    const x = umapData.filter((_, j) => mask[j]).map(p => p[0]);
    const y = umapData.filter((_, j) => mask[j]).map(p => p[1]);
    return {{ x, y, name, mode: 'markers', type: 'scattergl',
              marker: {{ color: methodColors[i], size: 4, opacity: 0.6 }} }};
}});
Plotly.newPlot('plot-method', traceMethod, {{
    height: 500,
    margin: {{ l: 40, r: 20, t: 10, b: 40 }},
    xaxis: {{ title: 'UMAP-1', showgrid: false, zeroline: false, color: colors.font_color }},
    yaxis: {{ title: 'UMAP-2', showgrid: false, zeroline: false, color: colors.font_color }},
    plot_bgcolor: colors.plot_bgcolor,
    paper_bgcolor: colors.paper_bgcolor,
    font: {{ color: colors.font_color }},
    legend: {{ x: 1, y: 1, bgcolor: colors.legend_bg }},
}}, {{ responsive: true }});

// UMAP by cluster
const uniqueClusters = [...new Set(clusterArr)].filter(c => c !== -1).sort();
const noise = clusterArr.filter(c => c === -1).length;
var traceCluster = [];
if (noise > 0) {{
    const x = umapData.filter((_, j) => clusterArr[j] === -1).map(p => p[0]);
    const y = umapData.filter((_, j) => clusterArr[j] === -1).map(p => p[1]);
    traceCluster.push({{ x, y, name: 'Noise (' + noise.toLocaleString() + ')', mode: 'markers', type: 'scattergl',
                        marker: {{ color: '#94a3b8', size: 3, opacity: 0.3 }} }});
}}
uniqueClusters.forEach((cid, idx) => {{
    const x = umapData.filter((_, j) => clusterArr[j] === cid).map(p => p[0]);
    const y = umapData.filter((_, j) => clusterArr[j] === cid).map(p => p[1]);
    traceCluster.push({{ x, y, name: 'CL-' + String(cid).padStart(3,'0'), mode: 'markers',
                        type: 'scattergl',
                        marker: {{ color: clusterPalette[idx % clusterPalette.length], size: 4, opacity: 0.7 }} }});
}});
Plotly.newPlot('plot-cluster', traceCluster, {{
    height: 500,
    margin: {{ l: 40, r: 20, t: 10, b: 40 }},
    xaxis: {{ title: 'UMAP-1', showgrid: false, zeroline: false, color: colors.font_color }},
    yaxis: {{ title: 'UMAP-2', showgrid: false, zeroline: false, color: colors.font_color }},
    plot_bgcolor: colors.plot_bgcolor,
    paper_bgcolor: colors.paper_bgcolor,
    font: {{ color: colors.font_color }},
    legend: {{ x: 1, y: 1, bgcolor: colors.legend_bg }},
}}, {{ responsive: true }});

// Cluster distribution
const pc = stats.per_cluster;
const clusterSizes = pc.map(c => c.size);
const clusterLabels = pc.map(c => 'CL-' + String(c.cluster_id).padStart(3,'0'));
Plotly.newPlot('plot-dist', [{{
    x: clusterLabels, y: clusterSizes, type: 'bar',
    marker: {{ color: clusterPalette.slice(0, clusterLabels.length) }},
}}], {{
    height: 400,
    margin: {{ l: 40, r: 20, t: 10, b: 80 }},
    xaxis: {{ title: '', tickangle: -45, color: colors.font_color }},
    yaxis: {{ title: 'Cluster Size', color: colors.font_color, showgrid: true, gridcolor: colors.grid_color }},
    plot_bgcolor: colors.plot_bgcolor,
    paper_bgcolor: colors.paper_bgcolor,
    font: {{ color: colors.font_color }},
}}, {{ responsive: true }});

// Shared Cluster Analysis
const sca = stats.shared_cluster_analysis;
const badgeClass = {{ 'LabIR': 'badge-labir', 'SPIR': 'badge-spir', 'SA': 'badge-sa', 'Mono': 'badge-mono' }};
if (sca && sca.summary) {{
    // Summary stats
    const summaryHTML = [
        {{ label: 'Tier 1 (All Methods)', value: sca.summary.tier_1_all_methods }},
        {{ label: 'Tier 2 (3 Methods)', value: sca.summary.tier_2_three_methods }},
        {{ label: 'Tier 3 (2 Methods)', value: sca.summary.tier_3_two_methods }},
        {{ label: 'Tier 4 (BF Only)', value: sca.summary.tier_4_bf_only }},
        {{ label: 'Tier 5 (Mono/SA Only)', value: sca.summary.tier_5_mono_sa_only }},
    ].map(s => `<div class="stat-card"><div class="stat-value">${{s.value}}</div><div class="stat-label">${{s.label}}</div></div>`).join('');
    document.getElementById('shared-summary').innerHTML = summaryHTML;
    
    // Top shared clusters table (Tier 1-3)
    const sharedClusters = sca.clusters
        .filter(c => c.tier <= 3)
        .sort((a, b) => b.size - a.size)
        .slice(0, 20);
    
    if (sharedClusters.length > 0) {{
        const tableHTML = `<table>
            <thead>
                <tr>
                    <th>Cluster</th>
                    <th>Tier</th>
                    <th>Size</th>
                    <th>Methods</th>
                    <th>Avg Coherence</th>
                    <th>Unique Azimuths</th>
                </tr>
            </thead>
            <tbody>
            ${{sharedClusters.map(c => {{
                const methodBadges = Object.entries(c.methods_present)
                    .map(([m, count]) => `<span class="badge ${{badgeClass[m] || ''}}">${{m}} (${{count}})</span>`)
                    .join(' ');
                const coherenceValues = Object.values(c.coherence_per_method).filter(v => v !== null);
                const avgCoherence = coherenceValues.length > 0 
                    ? (coherenceValues.reduce((a, b) => a + b, 0) / coherenceValues.length).toFixed(3)
                    : 'N/A';
                return `<tr>
                    <td>CL-${{String(c.cluster_id).padStart(3, '0')}}</td>
                    <td>Tier ${{c.tier}}</td>
                    <td>${{c.size.toLocaleString()}}</td>
                    <td>${{methodBadges}}</td>
                    <td>${{avgCoherence}}</td>
                    <td>${{c.angular_diversity.unique_azimuths}}</td>
                </tr>`;
            }}).join('')}}
            </tbody>
        </table>`;
        document.getElementById('table-shared-clusters').innerHTML = tableHTML;
    }}
    
    // Angular diversity plot
    const clustersWithAzimuth = sca.clusters.filter(c => c.angular_diversity.unique_azimuths > 0);
    if (clustersWithAzimuth.length > 0) {{
        const angularData = clustersWithAzimuth
            .sort((a, b) => b.angular_diversity.unique_azimuths - a.angular_diversity.unique_azimuths)
            .slice(0, 15);
        
        Plotly.newPlot('plot-angular', [{{
            x: angularData.map(c => 'CL-' + String(c.cluster_id).padStart(3, '0')),
            y: angularData.map(c => c.angular_diversity.unique_azimuths),
            type: 'bar',
            marker: {{ color: '#8b5cf6' }},
            text: angularData.map(c => c.angular_diversity.azimuths.join(', ')),
            textposition: 'none',
            hovertemplate: 'Cluster: %{{x}}<br>Unique Azimuths: %{{y}}<br>Azimuths: %{{text}}<extra></extra>',
        }}], {{
            height: 350,
            margin: {{ l: 40, r: 20, t: 10, b: 80 }},
            xaxis: {{ title: '', tickangle: -45, color: colors.font_color }},
            yaxis: {{ title: 'Unique Azimuths', color: colors.font_color, showgrid: true, gridcolor: colors.grid_color }},
            plot_bgcolor: colors.plot_bgcolor,
            paper_bgcolor: colors.paper_bgcolor,
            font: {{ color: colors.font_color }},
        }}, {{ responsive: true }});
    }}
    
    // Within-cluster coherence plot for shared clusters
    const topShared = sca.clusters
        .filter(c => c.tier <= 3 && Object.keys(c.coherence_per_method).length > 0)
        .sort((a, b) => b.size - a.size)
        .slice(0, 10);
    
    if (topShared.length > 0) {{
        const coherenceTraces = methodNames.map((method, i) => {{
            const values = topShared.map(c => c.coherence_per_method[method] || null);
            return {{
                x: topShared.map(c => 'CL-' + String(c.cluster_id).padStart(3, '0')),
                y: values,
                name: method,
                type: 'bar',
                marker: {{ color: methodColors[i] }},
            }};
        }});
        
        Plotly.newPlot('plot-coherence', coherenceTraces, {{
            height: 350,
            margin: {{ l: 40, r: 20, t: 10, b: 80 }},
            barmode: 'group',
            xaxis: {{ title: '', tickangle: -45, color: colors.font_color }},
            yaxis: {{ title: 'Cosine Similarity', color: colors.font_color, showgrid: true, gridcolor: colors.grid_color, range: [0, 1] }},
            plot_bgcolor: colors.plot_bgcolor,
            paper_bgcolor: colors.paper_bgcolor,
            font: {{ color: colors.font_color }},
            legend: {{ x: 1, y: 1, bgcolor: 'rgba(0,0,0,0)' }},
        }}, {{ responsive: true }});
    }}
}}

// Noise Distance Analysis
const noiseAnalysis = stats.noise_analysis;
if (noiseAnalysis && noiseAnalysis.available) {{
    // Per-method noise distance chart
    const noiseMethodData = noiseAnalysis.per_method;
    if (noiseMethodData && noiseMethodData.length > 0) {{
        const nmMethods = noiseMethodData.map(d => d.method);
        const nmValues = noiseMethodData.map(d => d.mean_noise_distance);
        Plotly.newPlot('plot-noise-dist-method', [{{
            x: nmMethods, y: nmValues, type: 'bar',
            marker: {{ color: methodColors.slice(0, nmMethods.length) }},
            text: nmValues.map(v => v.toFixed(4)), textposition: 'outside',
        }}], {{
            height: 350,
            margin: {{ l: 40, r: 40, t: 10, b: 40 }},
            xaxis: {{ title: '', color: colors.font_color }},
            yaxis: {{ title: 'Cosine Distance from Noise', color: colors.font_color,
                      showgrid: true, gridcolor: colors.grid_color,
                      range: [0, 1] }},
            plot_bgcolor: colors.plot_bgcolor,
            paper_bgcolor: colors.paper_bgcolor,
            font: {{ color: colors.font_color }},
        }}, {{ responsive: true }});
    }}
    
    // Per-cluster noise distance for top shared clusters
    const clusterNoiseData = noiseAnalysis.per_cluster;
    if (clusterNoiseData && clusterNoiseData.length > 0 && sca) {{
        // Get top shared clusters
        const topSharedIds = new Set(sca.clusters
            .filter(c => c.tier <= 3)
            .sort((a, b) => b.size - a.size)
            .slice(0, 10)
            .map(c => c.cluster_id));
        
        const topClusterNoise = clusterNoiseData
            .filter(c => topSharedIds.has(c.cluster_id))
            .sort((a, b) => b.size - a.size);
        
        if (topClusterNoise.length > 0) {{
            Plotly.newPlot('plot-noise-dist-cluster', [{{
                x: topClusterNoise.map(c => 'CL-' + String(c.cluster_id).padStart(3, '0')),
                y: topClusterNoise.map(c => c.mean_noise_distance),
                type: 'bar',
                marker: {{ color: '#ef4444' }},
                text: topClusterNoise.map(c => c.mean_noise_distance.toFixed(3)),
                textposition: 'outside',
            }}], {{
                height: 350,
                margin: {{ l: 40, r: 40, t: 10, b: 80 }},
                xaxis: {{ title: '', tickangle: -45, color: colors.font_color }},
                yaxis: {{ title: 'Cosine Distance from Noise', color: colors.font_color,
                          showgrid: true, gridcolor: colors.grid_color,
                          range: [0, 1] }},
                plot_bgcolor: colors.plot_bgcolor,
                paper_bgcolor: colors.paper_bgcolor,
                font: {{ color: colors.font_color }},
            }}, {{ responsive: true }});
        }}
    }}
}}

// Noise Distance — Top Shared Clusters card
const noiseShared = noiseAnalysis && noiseAnalysis.top_shared_clusters;
if (noiseShared && noiseShared.length > 0) {{
    document.getElementById('noise-shared-heading').style.display = 'block';
    document.getElementById('noise-shared-desc').style.display = 'block';
    document.getElementById('card-noise-shared').style.display = 'block';

    const topSharedMethodColors = {{
        'bf_LabIR': '#1f77b4',
        'bf_SPIR': '#ff7f0e',
        'sa': '#2ca02c',
        'mono': '#d62728',
    }};

    const maxND = Math.max(...noiseShared.map(c => c.mean_noise_distance));

    const clusterRows = noiseShared.map(c => {{
        const tierClass = 'tier-' + c.tier;
        const segments = c.method_breakdown.map(mb => {{
            const barW = maxND > 0 ? (mb.noise_distance / maxND) * 100 : 0;
            return '<div class="noise-bar-segment" style="' +
                'width:' + barW + '%;' +
                'background:' + (topSharedMethodColors[mb.method] || '#94a3b8') + ';' +
                '" title="' + mb.method + ': ' + mb.noise_distance.toFixed(3) + '"></div>';
        }}).join('');

        const detailRows = c.method_breakdown.map(mb => {{
            const colour = topSharedMethodColors[mb.method] || '#94a3b8';
            return '<div class="noise-detail-row">' +
                '<div class="noise-detail-colour" style="background:' + colour + ';"></div>' +
                '<span class="noise-detail-method">' + mb.method + '</span>' +
                '<span class="noise-detail-n">n=' + mb.n + '</span>' +
                '<span class="noise-detail-val">' + mb.noise_distance.toFixed(4) + '</span>' +
                '</div>';
        }}).join('');

        return '<div class="noise-cluster-row" onclick="toggleNoiseDetail(this)">' +
            '<div class="noise-cluster-header">' +
                '<span class="noise-tier-badge ' + tierClass + '">T' + c.tier + '</span>' +
                '<span class="noise-cluster-name">CL-' + String(c.cluster_id).padStart(3, '0') + '</span>' +
                '<span class="noise-cluster-size">' + c.size.toLocaleString() + ' pts</span>' +
                '<div class="noise-bar-wrapper">' + segments + '</div>' +
            '</div>' +
            '<div class="noise-detail">' + detailRows + '</div>' +
        '</div>';
    }}).join('');

    document.getElementById('noise-shared-list').innerHTML = clusterRows;
}}

function toggleNoiseDetail(row) {{
    const detail = row.querySelector('.noise-detail');
    if (detail) {{
        detail.classList.toggle('visible');
    }}
}}
</script>

</body>
</html>"""


# ── Main ────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(description="PoC clustering and visualisation")
    parser.add_argument("--embeddings", type=str, default=None,
                        help="Directory containing *_embeddings.npy files "
                             "(or omit and use --location for multi-backend resolve)")
    parser.add_argument("--location", type=str, default=None,
                        help="Site code (e.g. 2A400); with embedding_io multi-backend load")
    parser.add_argument("--data-dir", type=str, default=None,
                        help="ANALYSIS_OUTPUT root (default from config)")
    parser.add_argument("--backends", type=str, default=None,
                        help="Comma list: birdnet_native,bacpipe,legacy "
                             "(default: auto-resolve)")
    parser.add_argument("--bacpipe-models", type=str, default=None,
                        help="Comma list of bacpipe model folder names under embeddings/bacpipe/")
    parser.add_argument("--date", type=str, default=None,
                        help="Date filter, comma-separated")
    parser.add_argument("--methods", type=str, default="bf_LabIR,bf_SPIR,sa,mono",
                        help="Methods to include")
    parser.add_argument("--min-cluster-size", type=int, default=5,
                        help="HDBSCAN min_cluster_size")
    parser.add_argument("--umap-n-neighbors", type=int, default=30,
                        help="UMAP n_neighbors")
    parser.add_argument("--output", type=str, default=None,
                        help="Output HTML path (default: embeddings dir / poc_dashboard.html)")
    parser.add_argument("--redesign", action="store_true",
                        help="Regenerate HTML from cached results (skips UMAP/HDBSCAN)")
    parser.add_argument("--cache-dir", type=str, default=None,
                        help="Directory for cache files (default: embeddings dir)")
    args = parser.parse_args()

    methods = [m.strip() for m in args.methods.split(",")]
    date_filter = [d.strip() for d in args.date.split(",")] if args.date else None

    # Resolve primary embeddings dir for cache/output defaults
    emb_dir = args.embeddings
    if emb_dir is None and args.location:
        data_root = args.data_dir or ANALYSIS_OUTPUT
        emb_dir = os.path.join(data_root, args.location, "embeddings")
    if emb_dir is None:
        print("❌ Provide --embeddings DIR or --location SITE")
        sys.exit(2)

    cache_dir = args.cache_dir or emb_dir

    # ── Redesign mode: load cache, regenerate HTML ──────────
    if args.redesign:
        cache_path = os.path.join(cache_dir, CACHE_SUFFIX)
        if not os.path.isfile(cache_path):
            print(f"❌ No cache found at {cache_path}")
            print("   Run without --redesign first to compute results and cache them.")
            sys.exit(1)
        print(f"Loading cached results from {cache_path}...")
        umap_2d, y_method, method_names, cluster_labels, stats, emb_dir_c = load_cache(cache_path)
        print(f"  ✓ Loaded {len(umap_2d):,} points, {stats['overview']['n_clusters']} clusters")
        print("Generating HTML dashboard (from cache)...")
        output_path = args.output or os.path.join(emb_dir, "poc_dashboard.html")
        html = generate_html(emb_dir_c, umap_2d, y_method, method_names,
                             cluster_labels, stats)
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(html)
        print(f"\n✅ Dashboard written to: {output_path}  ({len(html):,} bytes)")
        return

    # ── Full computation mode ───────────────────────────────

    print(f"Methods: {methods}")
    if date_filter:
        print(f"Dates: {date_filter}")

    t0 = time.time()
    # Multi-backend resolve when --location set without exclusive single-dir mode
    use_multi = args.location is not None and (
        args.backends is not None
        or args.bacpipe_models is not None
        or args.embeddings is None
    )
    if use_multi:
        from embedding_io import load_location_embeddings

        data_root = args.data_dir or ANALYSIS_OUTPUT
        backends = (
            [b.strip() for b in args.backends.split(",") if b.strip()]
            if args.backends
            else None
        )
        bp_models = (
            [m.strip() for m in args.bacpipe_models.split(",") if m.strip()]
            if args.bacpipe_models
            else None
        )
        packed = load_location_embeddings(
            data_root,
            args.location,
            methods=methods,
            date_filter=date_filter,
            embeddings_path=args.embeddings,
            backends=backends,
            bacpipe_models=bp_models,
        )
        X = packed["X"]
        y_method = packed["y_method"]
        flat_meta = packed["flat_meta"]
        method_names = packed["methods"]
        embeddings = {}  # not used downstream as dict in current flow
        print(f"Sources: {packed['per_source']}")
    else:
        print(f"Loading embeddings from: {emb_dir}")
        embeddings, X, y_method, flat_meta, method_names = load_embeddings(
            emb_dir, methods, date_filter
        )

    if len(X) == 0:
        print("❌ No embeddings found!")
        sys.exit(1)

    total = len(X)
    print(f"Loaded {total:,} embeddings in {time.time() - t0:.1f}s")

    # ── UMAP ──────────────────────────────
    print(f"Running UMAP (n_neighbors={args.umap_n_neighbors})...")
    t1 = time.time()
    umap_2d = run_umap(X, n_neighbors=args.umap_n_neighbors)
    print(f"  ✓ UMAP done in {time.time() - t1:.1f}s")

    # ── HDBSCAN ──────────────────────────────
    print(f"Running HDBSCAN on UMAP 2D (min_cluster_size={args.min_cluster_size})...")
    t2 = time.time()
    cluster_labels = run_hdbscan(umap_2d, min_cluster_size=args.min_cluster_size,
                                 min_samples=max(1, args.min_cluster_size // 2))
    print(f"  ✓ HDBSCAN done in {time.time() - t2:.1f}s")

    # ── Statistics ──────────────────────────────
    print("Computing statistics...")
    stats = compute_stats(X, y_method, method_names, cluster_labels,
                         embeddings=embeddings)
    
    # ── Shared Cluster & Angular Diversity Analysis ──────
    print("Computing shared cluster analysis...")
    shared_analysis = compute_shared_cluster_analysis(
        X, cluster_labels, y_method, method_names, flat_meta
    )
    stats['shared_cluster_analysis'] = shared_analysis
    
    # ── Noise Reference Analysis ──────────────────────
    noise_vectors = load_noise_embeddings(args.embeddings)
    if noise_vectors:
        print("\nComputing noise distance analysis...")
        noise_analysis = compute_noise_distance(
            X, y_method, method_names, cluster_labels, noise_vectors,
            shared_analysis=shared_analysis
        )
        stats['noise_analysis'] = noise_analysis
        print(f"  ✓ Noise distance computed")
    else:
        print("\n  (No noise reference embeddings found — skipping noise analysis)")
        stats['noise_analysis'] = {"available": False}
    
    summary = shared_analysis['summary']
    print(f"\nShared Cluster Stratification:")
    print(f"  Tier 1 (all 4 methods): {summary['tier_1_all_methods']}")
    print(f"  Tier 2 (3 methods):     {summary['tier_2_three_methods']}")
    print(f"  Tier 3 (2 methods):     {summary['tier_3_two_methods']}")
    print(f"  Tier 4 (bf-only):       {summary['tier_4_bf_only']}")
    print(f"  Tier 5 (mono/sa-only):  {summary['tier_5_mono_sa_only']}")
    print(f"  Noise:                  {summary['noise']}")

    print(f"\nOverview:")
    print(f"  Total embeddings: {stats['overview']['total_embeddings']:,}")
    print(f"  Clusters found:   {stats['overview']['n_clusters']}")
    print(f"  Noise:            {stats['overview']['noise_pct']}%")
    print(f"\nPer-method (SNR proxy: ↑ cosine sim = better SNR, ↓ noise% = better SNR):")
    for pm in stats["per_method"]:
        cs = pm.get("cosine_sim", 0)
        print(f"  {pm['method']:>6s}: {pm['n_embeddings']:>6,} embeddings, "
              f"CosSim={cs:.3f}  Noise={pm['noise_pct']:>5.1f}%  "
              f"{pm['n_unique_clusters']} clusters")

    # ── HTML ──────────────────────────────
    print("Generating HTML dashboard...")
    output_path = args.output or os.path.join(args.embeddings, "poc_dashboard.html")
    html = generate_html(args.embeddings, umap_2d, y_method, method_names,
                        cluster_labels, stats)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(html)

    print(f"\n✅ Dashboard written to: {output_path}  ({len(html):,} bytes)")

    # Save cache for future --redesign runs
    try:
        cache_path = os.path.join(cache_dir, CACHE_SUFFIX)
        save_cache(cache_path, args.embeddings, umap_2d, y_method,
                   method_names, cluster_labels, stats)
    except Exception as e:
        print(f"  ⚠️  Cache save failed: {e}")

    print(f"   Total time: {time.time() - t0:.1f}s")


if __name__ == "__main__":
    main()
