#!/usr/bin/env python
"""Is the second peak a second source, or the array's own image of the first?

A single source can produce a spurious peak at a fixed angular offset, so the
persistence of a second peak on its own does not establish a second bird. Two
things separate the explanations.

The offset histogram. An array artefact sits at one angle, most likely near 180
degrees; genuine second sources are spread over the sphere.

The conditional concentration. If the second peak is an image of the first, then
knowing the first direction fixes the second. So the share of the most common
second direction is compared given the first direction, against the same share
computed ignoring it. A large gap means the pair is generated by the array.
"""
import argparse, json, os, sys
from collections import Counter, defaultdict
import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from embedding_io import load_embeddings_from_dir
from embedding_schema import audits_dir, bacpipe_embeddings_dir, bacpipe_meta_dir
from permutation_null import IncompletePairing, METHODS, build_windows, matrix_for
from beam_confidence import load_head, confidence
from multipeak import angles, sphere_sep, SEPARATION_DEG

BINS = list(range(90, 190, 15))


def run(data_dir, location, date_str, model, method, seed=0):
    src = bacpipe_embeddings_dir(data_dir, location, model)
    meta = bacpipe_meta_dir(location, model)
    _e, X, _y, fm, mn = load_embeddings_from_dir(
        src, methods=METHODS, date_filter=[date_str],
        source_tag=f"bacpipe:{model}", meta_dir=meta)
    if len(X) == 0:
        return {"model": model, "date": date_str, "method": method, "available": False}
    head = load_head(os.path.dirname(os.path.abspath(__file__)), model)
    conf, _t, _a, _b = confidence(X, head, seed)
    del X
    win, order = build_windows(fm, conf, mn)
    got = matrix_for(win, order, method)
    if got is None:
        return {"model": model, "date": date_str, "method": method,
                "available": False, "reason": f"{method} tidak terpasang"}
    D, beams = got["D"], got["beams"]
    coords = [angles(b) for b in beams]
    if any(c is None for c in coords):
        return {"model": model, "date": date_str, "method": method,
                "available": False, "reason": "tag arah tidak terbaca"}
    n_b = len(beams)
    sep = np.array([[sphere_sep(coords[i], coords[j]) for j in range(n_b)]
                    for i in range(n_b)])

    Db = D - D.mean(axis=0, keepdims=True)
    first = Db.argmax(axis=1)
    second = np.full(len(Db), -1, dtype=np.int64)
    for w in range(len(Db)):
        far = np.where(sep[first[w]] >= SEPARATION_DEG)[0]
        if len(far):
            second[w] = far[np.argmax(Db[w, far])]
    keep = (second >= 0) & (Db[np.arange(len(Db)), np.maximum(second, 0)] > 0)
    f, s = first[keep], second[keep]
    if len(f) < 200:
        return {"model": model, "date": date_str, "method": method,
                "available": False, "reason": f"hanya {len(f)} window"}

    offs = sep[f, s]
    hist = {}
    for lo in BINS:
        hi = lo + 15
        hist[f"{lo}-{hi}"] = round(100.0 * float(((offs >= lo) & (offs < hi)).mean()), 1)

    # The set of directions at least SEPARATION_DEG away depends on the first
    # direction, so a global baseline overstates concentration: part of it is
    # forced by the grid. The baseline below is a uniform pick among exactly the
    # directions that were admissible for that first direction.
    by_first = defaultdict(list)
    for a, b in zip(f.tolist(), s.tolist()):
        by_first[a].append(b)
    shares, nulls, weights = [], [], []
    for a, bs in by_first.items():
        if len(bs) < 30:
            continue
        n_admissible = int((sep[a] >= SEPARATION_DEG).sum())
        if n_admissible < 2:
            continue
        shares.append(Counter(bs).most_common(1)[0][1] / len(bs))
        # expected share of the most common of n_admissible uniform draws,
        # for a sample of len(bs); approximated by the uniform rate itself,
        # which is the honest floor for "no preference at all"
        nulls.append(1.0 / n_admissible)
        weights.append(len(bs))
    cond = float(np.average(shares, weights=weights)) if shares else float("nan")
    uncond = float(np.average(nulls, weights=weights)) if nulls else float("nan")

    return {
        "model": model, "date": date_str, "method": method, "available": True,
        "n_pairs": int(len(f)), "n_beams": n_b,
        "offset_median_deg": round(float(np.median(offs)), 1),
        "offset_mean_deg": round(float(offs.mean()), 1),
        "offset_histogram_pct": hist,
        "pct_offset_within_20deg_of_180": round(
            100.0 * float((np.abs(offs - 180.0) <= 20.0).mean()), 1),
        "second_share_uniform_among_admissible": round(uncond, 3),
        "second_share_given_first": round(cond, 3),
        "concentration_ratio": round(cond / uncond, 2) if uncond > 0 else None,
        "n_admissible_median": int(np.median(
            [(sep[a] >= SEPARATION_DEG).sum() for a in by_first])),
        "n_first_directions_used": len(shares),
    }


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--data-dir", default=os.environ.get("ANALYSIS_OUTPUT", "."))
    ap.add_argument("--location", default="2A400")
    ap.add_argument("--dates", nargs="+", required=True)
    ap.add_argument("--models", nargs="+", default=["birdnet", "avesecho_passt"])
    ap.add_argument("--methods", nargs="+", default=["bf_LabIR", "bf_SPIR"])
    ap.add_argument("--out", default=None)
    a = ap.parse_args()
    if not a.out:
        a.out = os.path.join(audits_dir(a.location), "peak_offset_geometry.json")
    res = {"location": a.location, "results": []}
    for d in a.dates:
        for mo in a.models:
            for me in a.methods:
                try:
                    r = run(a.data_dir, a.location, d, mo, me)
                # An incomplete pairing is a protocol violation, not a model that
                # happens to fail. It must stop the run so the missing data gets made.
                except IncompletePairing:
                    raise
                except Exception as e:
                    r = {"model": mo, "date": d, "method": me,
                         "available": False, "reason": str(e)[:200]}
                res["results"].append(r)
                print(f"[{mo} {d} {me}] {'ok' if r.get('available') else r.get('reason','')}",
                      flush=True)
                with open(a.out, "w") as f:
                    json.dump(res, f, indent=2)
    print("wrote", a.out)


if __name__ == "__main__":
    main()
